name: UOConverter
main: ru.alastar.Main
author: Alastar
description: UOmap to minecraft
version: 2.0
depend: [WorldEdit]
load: POSTWORLD
commands:
     convertuo:
       description: creates copy of uo map in current world
       permission: UOC.convert
       usage: /convertuo <filename>